# Use the official Python base image
FROM python:3.9

# Set environment variables for Python buffering and encoding
ENV PYTHONUNBUFFERED 1
ENV PYTHONIOENCODING utf-8

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt /app/

# Install project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the project files to the container
COPY . /app/

# Expose the port used by the Django application
EXPOSE 5000

# Run the Django development server
CMD python manage.py runserver 0.0.0.0:5000
